const t={fa:{title:'پنل مدیریت',loginTitle:'ورود امن',usernameLabel:'نام کاربری',passwordLabel:'رمز عبور',captchaLabel:'کپچا',loginBtn:'ورود',logout:'خروج',ntpTitle:'تنظیمات NTP',ntpSave:'ذخیره',ntpTest:'تست',jsonTitle:'مدیریت فایل‌های JSON',jsonLoad:'بارگذاری',jsonSave:'ذخیره',passwordTitle:'تغییر رمز عبور اولیه',newPasswordLabel:'رمز عبور جدید',confirmPasswordLabel:'تکرار رمز عبور',passwordSave:'ذخیره رمز عبور',defaultsTitle:'تنظیمات پیش‌فرض برنامه',defaultCitiesLabel:'شهرهای پیش‌فرض (با کاما جدا کنید)',defaultSelectedCityLabel:'شهر اولیه کاربر',defaultOccasionsLabel:'فیلترهای پیش‌فرض مناسبت‌ها (با کاما)',defaultsSaveBtn:'ذخیره تنظیمات پیش‌فرض',defaultNote:'اعتبار پیش‌فرض: admin / ChangeMe123! . لطفا بعد از اولین ورود تغییر دهید.',forcePasswordInfo:'برای ادامه، ابتدا باید رمز عبور اولیه را تغییر دهید.'},en:{title:'Admin Panel',loginTitle:'Secure Login',usernameLabel:'Username',passwordLabel:'Password',captchaLabel:'Captcha',loginBtn:'Login',logout:'Logout',ntpTitle:'NTP Settings',ntpSave:'Save',ntpTest:'Test',jsonTitle:'JSON Files Manager',jsonLoad:'Load',jsonSave:'Save',passwordTitle:'Change initial password',newPasswordLabel:'New password',confirmPasswordLabel:'Repeat password',passwordSave:'Save password',defaultsTitle:'App defaults',defaultCitiesLabel:'Default cities (comma separated)',defaultSelectedCityLabel:'Initial default city',defaultOccasionsLabel:'Default occasion filters (comma separated)',defaultsSaveBtn:'Save app defaults',defaultNote:'Default credentials: admin / ChangeMe123! Please change after first login.',forcePasswordInfo:'You must change the initial password first to continue.'}};
let lang='fa';const $=i=>document.getElementById(i);const setStatus=(id,msg,type='')=>{const el=$(id);el.textContent=msg;el.className=`status ${type}`.trim();};
function applyLang(){const x=t[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';$('title').textContent=x.title;$('loginTitle').textContent=x.loginTitle;$('usernameLabel').textContent=x.usernameLabel;$('passwordLabel').textContent=x.passwordLabel;$('captchaLabel').textContent=x.captchaLabel;$('loginBtn').textContent=x.loginBtn;$('logoutBtn').textContent=x.logout;$('ntpTitle').textContent=x.ntpTitle;$('ntpSaveBtn').textContent=x.ntpSave;$('ntpTestBtn').textContent=x.ntpTest;$('jsonTitle').textContent=x.jsonTitle;$('jsonLoadBtn').textContent=x.jsonLoad;$('jsonSaveBtn').textContent=x.jsonSave;$('passwordTitle').textContent=x.passwordTitle;$('newPasswordLabel').textContent=x.newPasswordLabel;$('confirmPasswordLabel').textContent=x.confirmPasswordLabel;$('passwordSaveBtn').textContent=x.passwordSave;$('defaultsTitle').textContent=x.defaultsTitle;$('defaultCitiesLabel').textContent=x.defaultCitiesLabel;$('defaultSelectedCityLabel').textContent=x.defaultSelectedCityLabel;$('defaultOccasionsLabel').textContent=x.defaultOccasionsLabel;$('defaultsSaveBtn').textContent=x.defaultsSaveBtn;$('firstLoginNote').textContent=x.defaultNote;$('forcePasswordInfo').textContent=x.forcePasswordInfo;$('langToggle').textContent=lang==='fa'?'EN':'FA';}
async function api(path,opts={}){const r=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json'},...opts});const d=await r.json().catch(()=>({}));if(!r.ok) throw new Error(d.error||'Request failed');return d;}
async function refreshCaptcha(){const d=await api('/api/admin/captcha');$('captchaText').textContent=d.captcha;}
function setDashboard(mode){$('dashboard').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('forcePasswordCard').classList.toggle('hidden',mode!=='force');$('dashboardContent').classList.toggle('hidden',mode!=='full');}
async function checkAuth(){try{const s=await api('/api/admin/session');$('loginCard').classList.add('hidden');if(s.forcePasswordChange){setDashboard('force');setStatus('passwordStatus','', '');}else{setDashboard('full');await loadConfig();await loadJsonFiles();}}catch{}}
$('langToggle').onclick=()=>{lang=lang==='fa'?'en':'fa';applyLang();};$('refreshCaptcha').onclick=refreshCaptcha;
$('loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f.entries()))});setStatus('loginStatus',d.forcePasswordChange?'Login successful. Change password first.':'OK','ok');$('firstLoginNote').classList.remove('hidden');await checkAuth();}catch(err){setStatus('loginStatus',err.message,'err');await refreshCaptcha();}};
$('passwordForm').onsubmit=async e=>{e.preventDefault();if($('newPassword').value!==$('confirmPassword').value) return setStatus('passwordStatus',lang==='fa'?'عدم تطابق رمز عبور':'Passwords do not match','err');try{await api('/api/admin/change-password',{method:'POST',body:JSON.stringify({newPassword:$('newPassword').value})});setStatus('passwordStatus',lang==='fa'?'رمز عبور تغییر کرد':'Password changed','ok');setDashboard('full');await loadConfig();await loadJsonFiles();}catch(err){setStatus('passwordStatus',err.message,'err');}};
$('logoutBtn').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload();};
async function loadConfig(){const d=await api('/api/admin/config');$('ntpHost').value=d.ntpHost||'';$('defaultCitiesInput').value=(d.defaultCityIds||[]).join(',');$('defaultSelectedCityInput').value=d.defaultSelectedCityId||'';$('defaultOccasionsInput').value=(d.defaultOccasionTypes||[]).join(',');}
$('ntpForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/config',{method:'POST',body:JSON.stringify({ntpHost:$('ntpHost').value})});setStatus('ntpStatus','Saved','ok');}catch(err){setStatus('ntpStatus',err.message,'err');}};
$('ntpTestBtn').onclick=async()=>{try{const d=await api('/api/ntp?host='+encodeURIComponent($('ntpHost').value));setStatus('ntpStatus',new Date(d.time).toISOString(),'ok');}catch(err){setStatus('ntpStatus',err.message,'err');}};
async function loadJsonFiles(){const d=await api('/api/admin/json-files');$('jsonFileSelect').innerHTML=d.files.map(f=>`<option value="${f}">${f}</option>`).join('');if(d.files[0])loadJson(d.files[0]);}
async function loadJson(file){const d=await api('/api/admin/json-file?file='+encodeURIComponent(file));$('jsonEditor').value=JSON.stringify(d.content,null,2);}
$('jsonLoadBtn').onclick=()=>loadJson($('jsonFileSelect').value);
$('jsonSaveBtn').onclick=async()=>{try{const content=JSON.parse($('jsonEditor').value);await api('/api/admin/json-file',{method:'POST',body:JSON.stringify({file:$('jsonFileSelect').value,content})});setStatus('jsonStatus','Saved','ok');}catch(err){setStatus('jsonStatus',err.message,'err');}};
applyLang();refreshCaptcha();checkAuth();

$('defaultsForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/config',{method:'POST',body:JSON.stringify({ntpHost:$('ntpHost').value,defaultCityIds:$('defaultCitiesInput').value.split(',').map(v=>v.trim()).filter(Boolean),defaultSelectedCityId:$('defaultSelectedCityInput').value.trim(),defaultOccasionTypes:$('defaultOccasionsInput').value.split(',').map(v=>v.trim()).filter(Boolean)})});setStatus('defaultsStatus','Saved','ok');}catch(err){setStatus('defaultsStatus',err.message,'err');}};
