const $=id=>document.getElementById(id);
const githubStorageKey='time-admin-github-settings';
const i18n={
  fa:{loginTitle:'اتصال مدیریت به گیت‌هاب',help:'برای مدیریت داده‌ها روی GitHub Pages، مشخصات ریپازیتوری و یک fine-grained token با دسترسی Contents read/write را وارد کنید.',owner:'مالک ریپازیتوری',repo:'نام ریپازیتوری',branch:'برنچ',token:'توکن گیت‌هاب',loginBtn:'اتصال و ورود به داشبورد',forget:'پاک کردن اتصال',welcomeTitle:'مدیریت بدون سرور',welcomeDesc:'داده‌های سایت مستقیماً از همین مرورگر در GitHub commit می‌شوند و بعد از اجرای GitHub Pages workflow منتشر خواهند شد.',connecting:'در حال بررسی اتصال به GitHub...',connected:'اتصال برقرار شد؛ در حال انتقال به داشبورد...',removed:'اطلاعات اتصال از این مرورگر پاک شد.'},
  en:{loginTitle:'Connect Admin to GitHub',help:'To manage data on GitHub Pages, enter the repository details and a fine-grained token with Contents read/write access.',owner:'Repository owner',repo:'Repository name',branch:'Branch',token:'GitHub token',loginBtn:'Connect and open dashboard',forget:'Forget connection',welcomeTitle:'Serverless Admin',welcomeDesc:'Site data is committed to GitHub directly from this browser and is published after the GitHub Pages workflow finishes.',connecting:'Checking GitHub connection...',connected:'Connected; opening dashboard...',removed:'Connection details were removed from this browser.'}
};
function langPack(){return document.documentElement.lang==='fa'?i18n.fa:i18n.en;}
function apply(){const t=langPack();$('loginTitle').textContent=t.loginTitle;$('loginHelp').textContent=t.help;$('ownerLabel').textContent=t.owner;$('repoLabel').textContent=t.repo;$('branchLabel').textContent=t.branch;$('tokenLabel').textContent=t.token;$('loginBtn').textContent=t.loginBtn;$('forgetBtn').textContent=t.forget;$('welcomeTitle').textContent=t.welcomeTitle;$('welcomeDesc').textContent=t.welcomeDesc;}
function getSaved(){try{return JSON.parse(localStorage.getItem(githubStorageKey)||'{}')||{};}catch{return {};}}
function fillSaved(){const s=getSaved();$('githubOwner').value=s.owner||'';$('githubRepo').value=s.repo||'';$('githubBranch').value=s.branch||'main';$('githubToken').value=s.token||'';}
function save(settings){localStorage.setItem(githubStorageKey,JSON.stringify(settings));}
function headers(token){return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'};}
async function verify({owner,repo,branch,token}){const base=`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;const repoRes=await fetch(base,{headers:headers(token)});const repoData=await repoRes.json().catch(()=>({}));if(!repoRes.ok)throw new Error(repoData.message||'GitHub repository check failed');const branchRes=await fetch(`${base}/branches/${encodeURIComponent(branch)}`,{headers:headers(token)});const branchData=await branchRes.json().catch(()=>({}));if(!branchRes.ok)throw new Error(branchData.message||'GitHub branch check failed');return true;}
$('langToggle').onclick=()=>{const fa=document.documentElement.lang==='fa';document.documentElement.lang=fa?'en':'fa';document.documentElement.dir=fa?'ltr':'rtl';$('langToggle').textContent=fa?'FA':'EN';apply();};
$('forgetBtn').onclick=()=>{localStorage.removeItem(githubStorageKey);fillSaved();$('loginStatus').textContent=langPack().removed;};
$('loginForm').onsubmit=async e=>{e.preventDefault();const settings={owner:$('githubOwner').value.trim(),repo:$('githubRepo').value.trim(),branch:$('githubBranch').value.trim()||'main',token:$('githubToken').value.trim()};$('loginStatus').textContent=langPack().connecting;try{await verify(settings);save(settings);$('loginStatus').textContent=langPack().connected;location.href='/admin-dashboard.html';}catch(err){$('loginStatus').textContent=err.message||'GitHub connection failed';}};
apply();fillSaved();
